/*******************************************************************************
 * Copyright (c) 2009 Dmitry Grushin <dgrushin@gmail.com>.
 * 
 * This file is part of GridMe.
 * 
 * GridMe is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GridMe is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GridMe.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors:
 *     Dmitry Grushin <dgrushin@gmail.com> - initial API and implementation
 ******************************************************************************/
package com.googlecode.gridme.runtime;

/**
 * Utility methods to print headers, copyrights, etc.
 */
public class Branding
{
  public static final String HTML_FOOTER = "Generated by "
      + "<a href='http://gridme.googlecode.com'>" + "GridMe</a> "
      + "simulation framework. "
      + "Charts are generated by <a href='http://www.jfree.org/jfreechart'>"
      + "JFreeChart</a> free chart library.";

  /**
   * Returns info string for printing in console tools. 
   */
  public static String consoleInfo()
  {
    return "GridMe simulation framework (http://gridme.googlecode.com).\n"
        + "This program comes with ABSOLUTELY NO WARRANTY.\n"
        + "This is free software, and you are welcome\n"
        + "to redistribute it under certain conditions.";
  }

  /**
   * Constructs a string from the number of spaces.
   */
  public static String sps(int count)
  {
    StringBuilder s = new StringBuilder();
    for(int i = 0; i < count; i++)
    {
      s.append(" ");
    }
    return s.toString();
  }
}
